version: '3.9'

services:
  mongo:
    image: mongo:4.4.18
    ports:
      - 27017:27017
    volumes:
      - ./db/data:/data/db
      # - ./db/backup.agz:/database_backup/backup.agz # eventually restore from backup



